###
POST http://admin:admin@localhost:8080/products
Content-Type: application/json

{
  "code": "A123",
  "name": "something"
}

### INVALID
POST http://admin:admin@localhost:8080/products
Content-Type: application/json

{
  "code": "123",
  "name": ""
}
