logging:
  level:
    org:
      hibernate: INFO
#      springframework: DEBUG


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    password: mysecretpassword
    username: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    password: mysecretpassword
    user: postgres
