logging:
  level:
    org:
      hibernate: INFO
#      springframework: DEBUG


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
