logging:
  level:
    org:
      hibernate: INFO
#      springframework: DEBUG


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: mysecretpassword
