logging:
  level:
    org.hibernate: INFO

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    password: mysecretpassword
    username: postgres

#spring.r2dbc.url=r2dbc:${db.url}
#spring.r2dbc.username=${db.user}
#spring.r2dbc.password=${db.password}
