
logging:
  level:
    com:
      winc: INFO
    org:
      hibernate: INFO
#      springframework: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none

  datasource:
    url: jdbc:sqlserver://localhost:1433
    username: SA
    password: sqlserver2019!

  flyway:
    url: jdbc:sqlserver://localhost:1433
    user: SA
    password: sqlserver2019!

# Spring debugging
# debug: true
